// Code generated by godel-refreshables-plugin. DO NOT EDIT.

package librarypkg

import refreshable "github.com/palantir/pkg/refreshable"

type RefreshableLibraryStruct interface {
	refreshable.Refreshable
	CurrentLibraryStruct() LibraryStruct
	MapLibraryStruct(func(LibraryStruct) any) refreshable.Refreshable
	SubscribeToLibraryStruct(func(LibraryStruct)) (unsubscribe func())

	FieldA() refreshable.Int
}

type RefreshingLibraryStruct struct {
	refreshable.Refreshable
}

func NewRefreshingLibraryStruct(in refreshable.Refreshable) RefreshingLibraryStruct {
	return RefreshingLibraryStruct{Refreshable: in}
}

func (r RefreshingLibraryStruct) CurrentLibraryStruct() LibraryStruct {
	return r.Current().(LibraryStruct)
}

func (r RefreshingLibraryStruct) MapLibraryStruct(mapFn func(LibraryStruct) any) refreshable.Refreshable {
	return r.Map(func(i any) any {
		return mapFn(i.(LibraryStruct))
	})
}

func (r RefreshingLibraryStruct) SubscribeToLibraryStruct(consumer func(LibraryStruct)) (unsubscribe func()) {
	return r.Subscribe(func(i any) {
		consumer(i.(LibraryStruct))
	})
}

func (r RefreshingLibraryStruct) FieldA() refreshable.Int {
	return refreshable.NewInt(r.MapLibraryStruct(func(i LibraryStruct) any {
		return i.FieldA
	}))
}
