plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.55.0
        checksums:
          linux-arm64: 92963392dc6d060686789a447f8f992afd0e51ff335b17475976cf51ae02ba23
environment:
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - integration_test/testcode
