// Generated by godel-refreshable-plugin: do not edit.

package test2

import (
	library "github.com/palantir/godel-refreshables-plugin/integration_test/testcode/test1/librarypkg"
	refreshable "github.com/palantir/pkg/refreshable"
)

type RefreshableOtherStruct interface {
	refreshable.Refreshable
	CurrentOtherStruct() OtherStruct
	MapOtherStruct(func(OtherStruct) any) refreshable.Refreshable
	SubscribeToOtherStruct(func(OtherStruct)) (unsubscribe func())

	FieldA() refreshable.String
	FieldB() RefreshableLibraryStruct
}

type RefreshingOtherStruct struct {
	refreshable.Refreshable
}

func NewRefreshingOtherStruct(in refreshable.Refreshable) RefreshingOtherStruct {
	return RefreshingOtherStruct{Refreshable: in}
}

func (r RefreshingOtherStruct) CurrentOtherStruct() OtherStruct {
	return r.Current().(OtherStruct)
}

func (r RefreshingOtherStruct) MapOtherStruct(mapFn func(OtherStruct) any) refreshable.Refreshable {
	return r.Map(func(i any) any {
		return mapFn(i.(OtherStruct))
	})
}

func (r RefreshingOtherStruct) SubscribeToOtherStruct(consumer func(OtherStruct)) (unsubscribe func()) {
	return r.Subscribe(func(i any) {
		consumer(i.(OtherStruct))
	})
}

func (r RefreshingOtherStruct) FieldA() refreshable.String {
	return refreshable.NewString(r.MapOtherStruct(func(i OtherStruct) any {
		return i.FieldA
	}))
}

func (r RefreshingOtherStruct) FieldB() RefreshableLibraryStruct {
	return NewRefreshingLibraryStruct(r.MapOtherStruct(func(i OtherStruct) any {
		return i.FieldB
	}))
}

type RefreshableLibraryStruct interface {
	refreshable.Refreshable
	CurrentLibraryStruct() library.LibraryStruct
	MapLibraryStruct(func(library.LibraryStruct) any) refreshable.Refreshable
	SubscribeToLibraryStruct(func(library.LibraryStruct)) (unsubscribe func())

	FieldA() refreshable.Int
}

type RefreshingLibraryStruct struct {
	refreshable.Refreshable
}

func NewRefreshingLibraryStruct(in refreshable.Refreshable) RefreshingLibraryStruct {
	return RefreshingLibraryStruct{Refreshable: in}
}

func (r RefreshingLibraryStruct) CurrentLibraryStruct() library.LibraryStruct {
	return r.Current().(library.LibraryStruct)
}

func (r RefreshingLibraryStruct) MapLibraryStruct(mapFn func(library.LibraryStruct) any) refreshable.Refreshable {
	return r.Map(func(i any) any {
		return mapFn(i.(library.LibraryStruct))
	})
}

func (r RefreshingLibraryStruct) SubscribeToLibraryStruct(consumer func(library.LibraryStruct)) (unsubscribe func()) {
	return r.Subscribe(func(i any) {
		consumer(i.(library.LibraryStruct))
	})
}

func (r RefreshingLibraryStruct) FieldA() refreshable.Int {
	return refreshable.NewInt(r.MapLibraryStruct(func(i library.LibraryStruct) any {
		return i.FieldA
	}))
}
